version: '3.0'
services:
  db:
    container_name: db
    image: postgres:13-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5433:5432
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    restart: always
    env_file:
      - .env
    ports:
      - 8080:80
    volumes:
      - /var/lib/pgadmin
    depends_on:
      - db
